

name: Release

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: |
        npm install
    - name: Run roboter
      run: |
        npx roboter qa
    - name: Compile TypeScript
      run: |
        npx roboter build
    - name: Release
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}